Repository openyurtio/yurt-app-manager, pull requests merged in 2021-12, with the labels that each got.

#29 hotfix: Lables fix to Annotations
  pkg/yurtappmanager/controller/nodepool/nodepool_controller.go
Labels: approved, lgtm, size/XS

#28 use https[s] proxy in docker for release build if necessary
  hack/lib/release-images.sh
Labels: approved, kind/bug, lgtm, size/XS

#32 Add YurtIngress operator implementation
  cmd/yurt-app-manager/app/core.go
  config/yurt-app-manager/crd/bases/apps.openyurt.io_yurtingresses.yaml
  config/yurt-app-manager/crd/kustomization.yaml
  config/yurt-app-manager/crd/patches/cainjection_in_yurtingresses.yaml
  config/yurt-app-manager/crd/patches/webhook_in_yurtingresses.yaml
  config/yurt-app-manager/rbac/role.yaml
  config/yurt-app-manager/rbac/yurtingress_editor_role.yaml
  config/yurt-app-manager/rbac/yurtingress_viewer_role.yaml
  config/yurt-app-manager/webhook/manifests.yaml
  pkg/yurtappmanager/apis/apps/v1alpha1/yurtingress_types.go
  pkg/yurtappmanager/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/yurtappmanager/client/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/yurtappmanager/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/yurtappmanager/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_yurtingress.go
  pkg/yurtappmanager/client/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/yurtappmanager/client/clientset/versioned/typed/apps/v1alpha1/yurtingress.go
  pkg/yurtappmanager/client/informers/externalversions/apps/v1alpha1/interface.go
  pkg/yurtappmanager/client/informers/externalversions/apps/v1alpha1/yurtingress.go
  pkg/yurtappmanager/client/informers/externalversions/generic.go
  pkg/yurtappmanager/client/listers/apps/v1alpha1/expansion_generated.go
  pkg/yurtappmanager/client/listers/apps/v1alpha1/yurtingress.go
  pkg/yurtappmanager/constant/nginx-ingress-controller-tmpl.go
  pkg/yurtappmanager/controller/controllers.go
  pkg/yurtappmanager/controller/yurtingress/yurtingress_controller.go
  pkg/yurtappmanager/util/kubernetes/apply_addons.go
  pkg/yurtappmanager/util/kubernetes/util.go
  pkg/yurtappmanager/webhook/add_yurtingress.go
  pkg/yurtappmanager/webhook/yurtingress/mutating/webhooks.go
  pkg/yurtappmanager/webhook/yurtingress/mutating/yurtingress_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtingress/validating/webhooks.go
  pkg/yurtappmanager/webhook/yurtingress/validating/yurtingress_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtingress/validating/yurtingress_validating.go
Labels: approved, lgtm, size/XXL
