Repository openyurtio/yurt-app-manager, pull requests merged in 2022-09, with the labels that each got.

#114 node change nodepool taints should update
  pkg/yurtappmanager/controller/nodepool/nodepool_controller.go
  pkg/yurtappmanager/controller/nodepool/nodepool_controller_test.go
Labels: approved, kind/bug, lgtm, size/M

#115 Enhance: tolerate Job&Pod run on master in charts
  charts/yurt-app-manager/values.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#116 Set default chart image tag as 0.6.0
  charts/yurt-app-manager/Chart.yaml
  charts/yurt-app-manager/values.yaml
Labels: approved, lgtm, size/XS

#117 crd naming optimization
  config/yurt-app-manager/crd/bases/apps.openyurt.io_yurtingresses.yaml
  config/yurt-app-manager/webhook/manifests.yaml
  pkg/yurtappmanager/apis/apps/v1alpha1/yurtingress_types.go
Labels: approved, lgtm, size/L

#118 crd naming additional modifications
  charts/yurt-app-manager/crds/apps.openyurt.io_yurtingresses.yaml
Labels: approved, kind/feature, lgtm, size/M

#119 remove all_in_one.yaml
  config/setup/all_in_one.yaml
Labels: approved, lgtm, size/XXL

#120 improve the coverage of yurtappdaemon
  pkg/yurtappmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller_test.go
  pkg/yurtappmanager/controller/yurtingress/yurtingress_controller_test.go
Labels: approved, lgtm, size/L
