Repository openyurtio/yurt-app-manager, pull requests merged in 2022-08, with the labels that each got.

#59 yurtappdaemonset reconcile error process
  pkg/yurtappmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
Labels: approved, lgtm, size/S

#84 yurtappdaemon control null process
  pkg/yurtappmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
Labels: approved, lgtm

#81 use kube-webhook-certgen generate cert
  charts/yurt-app-manager/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/yurt-app-manager/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/yurt-app-manager/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/yurt-app-manager/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/yurt-app-manager/templates/admission-webhooks/job-patch/role.yaml
  charts/yurt-app-manager/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/yurt-app-manager/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/yurt-app-manager/templates/admission-webhooks/mutatingwebhookconfiguration.yaml
  charts/yurt-app-manager/templates/admission-webhooks/validatingwebhookconfiguration.yaml
  charts/yurt-app-manager/templates/admission-webhooks/webhookService.yaml
  charts/yurt-app-manager/templates/deployment.yaml
  charts/yurt-app-manager/templates/service.yaml
  charts/yurt-app-manager/values.yaml
  cmd/yurt-app-manager/app/core.go
  pkg/yurtappmanager/webhook/server.go
  pkg/yurtappmanager/webhook/util/configuration/configuration.go
  pkg/yurtappmanager/webhook/util/controller/webhook_controller.go
  pkg/yurtappmanager/webhook/util/generator/certgenerator.go
  pkg/yurtappmanager/webhook/util/generator/fake/certgenerator.go
  pkg/yurtappmanager/webhook/util/generator/selfsigned.go
  pkg/yurtappmanager/webhook/util/generator/util.go
  pkg/yurtappmanager/webhook/util/health/checker.go
  pkg/yurtappmanager/webhook/util/health/handler.go
  pkg/yurtappmanager/webhook/util/writer/atomic/atomic_writer.go
  pkg/yurtappmanager/webhook/util/writer/certwriter.go
  pkg/yurtappmanager/webhook/util/writer/error.go
  pkg/yurtappmanager/webhook/util/writer/fs.go
  pkg/yurtappmanager/webhook/util/writer/secret.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#87 add zzguang as one of owners of yurt-app-manager
  OWNERS
Labels: approved, lgtm, size/XS

#69 temporary disable path filter
  .github/workflows/sync-api.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#85 add yurtingress controller unit test
  pkg/yurtappmanager/controller/yurtingress/yurtingress_controller_test.go
Labels: approved, lgtm, size/XL

#89 add nodepool controoller unit test
  .gitignore
  pkg/yurtappmanager/controller/nodepool/nodepool_controller.go
  pkg/yurtappmanager/controller/nodepool/nodepool_controller_test.go
  pkg/yurtappmanager/controller/nodepool/nodepool_enqueue_handlers.go
  pkg/yurtappmanager/util/gate/custom_resource_gate.go
  pkg/yurtappmanager/util/gate/custom_resource_gate_test.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#94 enable ci to verify go.mod
  .github/workflows/ci.yaml
  Makefile
  hack/make-rules/verify_mod.sh
Labels: approved, kind/enhancement, lgtm, size/M

#88 validate and mutate webhook upgrade
  cmd/yurt-app-manager/app/core.go
  go.mod
  go.sum
  pkg/yurtappmanager/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/yurtappmanager/webhook/add_nodepool.go
  pkg/yurtappmanager/webhook/add_yurtappdaemon.go
  pkg/yurtappmanager/webhook/add_yurtappset.go
  pkg/yurtappmanager/webhook/add_yurtingress.go
  pkg/yurtappmanager/webhook/nodepool/mutating/nodepool_create_update_handler.go
  pkg/yurtappmanager/webhook/nodepool/mutating/webhooks.go
  pkg/yurtappmanager/webhook/nodepool/nodepool_validation.go
  pkg/yurtappmanager/webhook/nodepool/nodepool_webhook.go
  pkg/yurtappmanager/webhook/nodepool/validating/nodepool_create_update_handler.go
  pkg/yurtappmanager/webhook/nodepool/validating/webhooks.go
  pkg/yurtappmanager/webhook/server.go
  pkg/yurtappmanager/webhook/yurtappdaemon/mutating/webhooks.go
  pkg/yurtappmanager/webhook/yurtappdaemon/mutating/yurtappdaemon_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtappdaemon/validating/webhooks.go
  pkg/yurtappmanager/webhook/yurtappdaemon/validating/yurtappdaemon_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtappdaemon/yurtappdaemon_validation.go
  pkg/yurtappmanager/webhook/yurtappdaemon/yurtappdaemon_webhook.go
  pkg/yurtappmanager/webhook/yurtappdaemon/yurtappdaemon_webhook_test.go
  pkg/yurtappmanager/webhook/yurtappset/mutating/webhooks.go
  pkg/yurtappmanager/webhook/yurtappset/mutating/yurtappset_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtappset/validating/tmp.yaml
  pkg/yurtappmanager/webhook/yurtappset/validating/webhooks.go
  pkg/yurtappmanager/webhook/yurtappset/validating/yurtappset_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtappset/validating/yurtappset_validation_test.go
  pkg/yurtappmanager/webhook/yurtappset/yurtappset_validation.go
  pkg/yurtappmanager/webhook/yurtappset/yurtappset_webhook.go
  pkg/yurtappmanager/webhook/yurtappset/yurtappset_webhook_test.go
  pkg/yurtappmanager/webhook/yurtingress/mutating/webhooks.go
  pkg/yurtappmanager/webhook/yurtingress/mutating/yurtingress_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtingress/validating/webhooks.go
  pkg/yurtappmanager/webhook/yurtingress/validating/yurtingress_create_update_handler.go
  pkg/yurtappmanager/webhook/yurtingress/yurtingress_validating.go
  pkg/yurtappmanager/webhook/yurtingress/yurtingress_webhook.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#53 【FIX】fix yurt-app-daemon toleration
  pkg/yurtappmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller.go
Labels: approved, lgtm, size/XS

#95 fix: go mod tidy
  .codecov.yml
  go.mod
  go.sum
Labels: approved, kind/enhancement, lgtm, size/S

#93 build and push image when merge master
  .github/workflows/release.yaml
  charts/yurt-app-manager/Chart.yaml
  charts/yurt-app-manager/values.yaml
Labels: approved, size/S

#98 readd yurtingress webhook
  pkg/yurtappmanager/webhook/server.go
  pkg/yurtappmanager/webhook/yurtingress/yurtingress_webhook_test.go
Labels: approved, size/M

#101 Fix: update install all_in_one.yaml
  config/setup/all_in_one.yaml
Labels: approved, lgtm, size/L

#102 Fix: fix nodepool status update error
  pkg/yurtappmanager/controller/nodepool/nodepool_controller.go
Labels: approved, lgtm, size/XS

#86 add yurtappdaemon controller unit test
  pkg/yurtappmanager/controller/yurtappdaemon/revision_test.go
  pkg/yurtappmanager/controller/yurtappdaemon/util_test.go
  pkg/yurtappmanager/controller/yurtappdaemon/workloadcontroller/util_test.go
Labels: approved, lgtm, size/L

#105 allow custom config git version
  Makefile
  hack/dockerfiles/Dockerfile
Labels: approved, kind/enhancement, lgtm, size/XS

#54 【FIX】fix revisionHistoryLimit is not exist
  pkg/yurtappmanager/controller/uniteddeployment/revision.go
Labels: approved, lgtm, size/XS

#106 improve unit test coverage for yurtappdaemon
  pkg/yurtappmanager/controller/yurtappdaemon/nodepool_enqueue_handlers_test.go
Labels: approved, lgtm, size/M

#108 fix ci os image
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: approved, kind/enhancement, size/S

#107 add e2e test
  .github/workflows/e2e-test.yaml
  Makefile
  go.mod
  hack/lib/init.sh
  hack/make-rules/build-e2e.sh
  hack/run-e2e-tests.sh
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/nodepool/nodepool.go
  tests/e2e/util/ginkgowrapper/wrapper.go
  tests/e2e/util/nodepool_utils.go
  tests/e2e/util/test_utils.go
  tests/e2e/yurtappset/yurtappset.go
  tests/e2e/yurtconfig/yurtconfig.go
  tests/kind-conf.yaml
Labels: approved, kind/enhancement, lgtm, size/XXL

#109 update yurtappdaemon_controller_test.go
  pkg/yurtappmanager/controller/yurtappdaemon/nodepool_enqueue_handlers_test.go
  pkg/yurtappmanager/controller/yurtappdaemon/revision_test.go
  pkg/yurtappmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller_test.go
  pkg/yurtappmanager/controller/yurtappdaemon/workloadcontroller/workload_test.go
  pkg/yurtappmanager/controller/yurtappdaemon/yurtappdaemon_controller_test.go
Labels: approved, lgtm, size/XXL

#111 update yurtingress_controller_test.go
  pkg/yurtappmanager/controller/yurtingress/yurtingress_controller_test.go
Labels: approved, lgtm, size/M

#113 improve the coverage of yurtappset
  pkg/yurtappmanager/controller/yurtappset/adapter/deployment_adapter_test.go
  pkg/yurtappmanager/controller/yurtappset/adapter/statefulset_adapter_test.go
  pkg/yurtappmanager/controller/yurtappset/pool_controller_test.go
  pkg/yurtappmanager/controller/yurtappset/revision_test.go
  pkg/yurtappmanager/controller/yurtappset/yurtappset_controller_test.go
Labels: approved, lgtm, size/XXL
