Repository openyurtio/yurt-app-manager, pull requests merged in 2022-01, with the labels that each got.

#26 Initialize capabilities to support enabling containers[*].securityContext.privileged for UnitedDeployment
  pkg/yurtappmanager/webhook/server.go
Labels: approved, lgtm, size/S

#33 ingress: fix YurtIngress CR status update error
  pkg/yurtappmanager/controller/yurtingress/yurtingress_controller.go
Labels: approved, lgtm, size/S

#34 update README to add YurtAppDaemon and YurtIngress
  README.md
  docs/YurtAppDaemon.md
  docs/images/uniteddeployment.png
  docs/images/yurtappdaemon.png
  docs/yurt-app-manager-tutorial.md
Labels: approved, lgtm, size/L

#35 add 0.5.0 relase and all_in_one yaml
  config/setup/all_in_one.yaml
Labels: approved, lgtm, size/XL

#37 ingress: update yurtingress tutorial link
  docs/yurt-app-manager-tutorial.md
Labels: approved, lgtm, size/XS
