Repository openyurtio/yurt-app-manager, pull requests merged in 2022-07, with the labels that each got.

#64 fix release script error
  .github/workflows/release.yaml
Labels: approved, kind/enhancement, size/XS

#65 feat: sync api
  .github/workflows/sync-api.yaml
  hack/lib/sync.sh
Labels: approved, kind/feature, size/L

#66 sync bugfix
  .github/workflows/sync-api.yaml
  hack/lib/sync-api.sh
Labels: approved, kind/bug, kind/enhancement, lgtm, size/M

#71 gen all in one yamls
  Makefile
  config/setup/all_in_one.yaml
Labels: kind/feature, size/XXL

#70 sync chart to repo
  .github/workflows/sync-charts.yaml
  hack/lib/sync-charts.sh
Labels: approved, lgtm, size/M

#67 openyurt fuzzer feature
  go.mod
  tests/fuzz/Dockerfile.builder
  tests/fuzz/go.mod
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/oss_fuzz_run.sh
  tests/fuzz/yurtappdaemon_fuzzer.go
  tests/fuzz/yurtappset_fuzzer.go
Labels: approved, kind/enhancement, lgtm, size/L
